name: workflow-name
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World
        run: echo "main"
