name: workflow-name

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World
        run: echo "develop"
